### ISSUE TITLE
gatecli status throwing unsupported protocol scheme "tcp"

### ISSUE THREAD

**Issue by madanyc** [gatechain/gatechain-docs#5]
I have installed gatchain full node as per the document and I am getting error when I try to do get status. Please find below error

root@cloudshell:~/.gated$ gatecli status
ERROR: Get tcp://localhost:8080/v1/status: unsupported protocol scheme "tcp"

**Comment by madanyc** [comment]
However I am able to do following things:
1. create account using command gatecli create account
2. create consensus account on mainnet: gatecli con-account create address 
3. I also transferred GT token using gate chain wallet to the newly created account

Things not working:
Anything related to transactions are not happening. Please find below error
```
gatecli account show <address> --chain-id mainnet
ERROR: {"codespace":"framework","code":9,"message":"account gt11vmhch2r6kcvwgyf7l9g9e86lc7x52qmace0rlyvuudrszcfuchdpu8jejs33s3xxdswwe8 does not exist"}
```

**Comment by AllanAi** [comment]
It is because your node hasn't finished syncing yet. You can check the account information through the gatechain explorer temporarily: https://gatescan.org/address/gt11vmhch2r6kcvwgyf7l9g9e86lc7x52qmace0rlyvuudrszcfuchdpu8jejs33s3xxdswwe8 

The `gatecli status` command is not working now. We will fix it in the next release.

**Comment by madanyc** [comment]
Thank you @AllanAi! I will look forward to the next release.
